# This is a basic workflow to help you get started with Actions

name: Just BuildðŸ˜Ž

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          sdk: 10.0.22621.0
          toolset: 14.29 
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  # You may pin to the exact commit or the version.
  # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
      - uses: sudosubin/git-clone-action@v1.0.1
        with: 
            platform: 'github'
          
      - run: |
          git init
          git remote add origin https://github.com/ToyLopGo/Better-On-Psych
          ls
          haxe -version
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup -alias -y
          haxelib install linc_luajit
          haxelib install tjson
          haxelib install hxCodec
          haxelib install hxdiscord_rpc
          haxelib install flxanimate
          haxelib install polymod
          haxelib install faxe
          haxelib install extension-webm
          haxelib install hscript
          haxelib install BrewScript
          haxelib install SScript
          ls
          haxelib run lime build windows
        working-directory: ${{env.working-directory}}
