# This is a basic workflow to help you get started with Actions

name: Just BuildğŸ˜

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./
    steps:
      - name: just haxeğŸ˜‘
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: i dont love msvc ğŸ˜¡
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          sdk: 10.0.22621.0
          toolset: 14.29 
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: MAKE REPO FOLDERğŸ‘ğŸ‘ğŸ‘
      - run: |
          mkdir repo
      - name: WOW CLONEğŸ˜
      - uses: sudosubin/git-clone-action@v1.0.1
        with: 
            platform: 'github'
            path: './repo'
      - name: LIBRARIESğŸ˜ğŸ˜ğŸ˜
      - run: |
          git init
          git remote add origin https://github.com/ToyLopGo/Better-On-Psych
          ls
          haxe -version
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup -alias -y
          haxelib install linc_luajit
          haxelib install tjson
          haxelib install hxCodec
          haxelib install hxdiscord_rpc
          haxelib install flxanimate
          haxelib install polymod
          haxelib install faxe
          haxelib install extension-webm
          haxelib install hscript
          haxelib install BrewScript
          haxelib install SScript
      - name: OMG LSğŸ˜¯ğŸ˜¯ğŸ˜¯
      - run: |
          ls
      - name: Just BuildğŸ˜
      - run: |
          haxelib run lime build windows
        working-directory: ${{env.working-directory}}
