# This is a basic workflow to help you get started with Actions

name: Just BuildğŸ˜

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: html5-latest
    env:
      working-directory: ./
    steps:
      - uses: actions/checkout@v3
      
      - name: just haxeğŸ˜‘
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
          
      - name: MAKE REPO FOLDERğŸ‘ğŸ‘ğŸ‘
        run: |
          mkdir repo
          cd repo

      - name: WOW CLONEğŸ˜
        run: git clone https://github.com/ToyLopGo/Better-On-Psych.git
        
      - name: LIBRARIESğŸ˜ğŸ˜ğŸ˜
        run: |
          git init
          git remote add origin https://github.com/ToyLopGo/Better-On-Psych
          ls
          haxe -version
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup -alias -y
          haxelib install linc_luajit
          haxelib install tjson
          haxelib install hxCodec
          haxelib install hxdiscord_rpc
          haxelib install flxanimate
          haxelib install polymod
          haxelib install faxe
          haxelib install extension-webm
          haxelib install hscript
          haxelib install BrewScript
          haxelib install SScript
          
      - name: OMG LSğŸ˜¯ğŸ˜¯ğŸ˜¯
        run: |
          ls
          
      - name: Just BuildğŸ˜
        run: |
            haxelib run lime build html5
            
      - working-directory: ${{env.working-directory}}
